language: go
sudo: required
env:
  global:
  - CGO_ENABLED=0
  - GO111MODULE=on
  - secure: "KKZEf6MtQUX0aVPv7vT1h7JjgHbGH8goo0MSGxUmHeW01IS7bdPibw+QjkCxEeDYD5H9c5Uh4aVT0fOrJxHsWWlMW/Uvj+FHbXuwT6CVh/dIrnWq/1sUmdIO+n5QrURDHTxDfkhFF4Ozc1TOb8NBM/ggElQk7YVgNpIyEOanIpdsM4g/cutXNNnbxtMG5/pdfksrIZILf0TsyMQrDfQIYUiCbM5NnSFI5z3EXKY088ck0brpFCJe1O1j0cXbkqof4vSSBNI0LynmPXJ2oexmkVge3RhIiaNEau4RQ2L73ix2VPcXGxKiz9jK4X0GA/5qENSMfGmHOiIY0tDiNteEv56G0oay1DdTOwSzdt5RazkaVsicn2mHJ5998fBFcfgvV3cqJsj7noT5OxddaLhTCmhSfuoY/kXQ0OADNvPI1indVYljMsepboxtkT3tIKJX+rS2uR4wK0rR9At6KVTaZ2AbUuMg0YV7mCgnYiUmfsBHog8tHGjgMYVWZ3FgyHzv57tDE2RRGwM2TVGZwHZpsFUGuDlMThU/WN05dJvjqWIAClcO1XS8lXaZUGE63HZ0ny30NDTmPxyQ42qjUzhUWlUjf+sAkFV9uJbJIFQxJV6sHtQO64CLYuSWyz0PXcTX8zVk24we2qO0CyjrOddVDx9QN/d6DbQj6gIJjymjRj8="
  - secure: "t2+kPORzUb1Vo94NsAMmCjvvtQ04i4XdVJU+jQZCZos8wAAjtlElAPGDrh2rdVs3HsCb5Inkn90crsvRfnUQIRvbIUAN/NZqEg8c7ZfgM99tMFG7jW91ayKid5Lg4hpcP7K2XObSK8HWDH7djxr0zeXaoGsytTnmfHwewLcc5qiJluM3tNUQppXHd1rZhZzDG/POj7k6NnOyPnXlu0pcDRgpw1fX1vDkNGXI5Ywr4NMe8NEnXXsxyP6EYT+uZdpxLX3usFC9hWNW84883awdW1tZPdGN9bFf/u+Cdse/TcSXdtme1taB8XPyg0VmYAtJxFMVgVXcHt1VdU22h6Bskhg26Liwqz6wvNMzcNYEFdk6I5EBErrB8Yf1QMGl1aSbPCHQYf/d2NwJgRR9iZ3Lk8uzB+hbdigtCEn5XW4P+ojIah1kWqkWzp9dTRL61SK3pW83PUAaZBbk8BZXyLRPSanEfZ2UIP7rbZ3KALcE8JLer/mx5u9+tGH5ppcG3eE9WvMHQmju48W0/1xcxN3Q4+dAi/BeNLJ7xMcSCv/aDa0tIqI/zjlDSAPx7777A1Xzj+xzdsMvUXmpAdHBqQGEZTlg+UePbvxOAvUXXkEmpgCdpxJSzBuo8MDInC4rkvCNj/+En31mdAtAby97MdwpZ/FnhZuYPNuEzopwz7vmpME="
services:
- docker
matrix:
  include:
  - go: 1.16.x
    env:
    - LATEST=true
  - go: tip
  allow_failures:
  - go: tip
install:
- go mod download
- go get github.com/mitchellh/gox
script:
- go vet $(go list ./... | grep -v /vendor/)
- go test -v ./...
- if [ "${LATEST}" = "true" ]; then gox -os="linux darwin windows" -arch="amd64 386"
  -output="build/alertmanager-webhook-fcm.{{.OS}}.{{.Arch}}" -ldflags "-extldflags
  \"-static\" -X main.Rev=`git rev-parse --short HEAD`" -verbose ./...; fi
- if [ "${LATEST}" = "true" -a -n "${TRAVIS_TAG}" ]; then docker build -t "jaymedh/alertmanager-webhook-fcm:${TRAVIS_TAG}"
  .; fi
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: UkvJ2JkAdkGHBbRjbnAcmglzvs5Cb+fuTGg+7fSCHnhRULhdRvdAp8WZri0IjzWNxQlRssDvH2rzWc0lE0PSsGQtXoWrXfiJNASpDBnLlzoFnXI225/4phXuWTAqxmWz6vXpFOfvzlt+X22NpUO2qQdhwRvP7vbd2PTG4ki7a5kgBzJOeSLFbvxXY8Gl7Wvca1rVDkyG8HBALU5mehXluvM/mpf9uHnZGbg0+2ppWLIvH9oxhM2e2V5NOEu9keRjby20e4tMPdeY5xeYMmu83DFHECQuNd/M8aiT+sA9apNkaISOgXbcRh/YeGnuZ3wkG7uanZzMY3GpLY4g8akKFiy0VHJhj/4ifoCTPbdf6zaaWL0gNbbMilU9yTUtxpZpz7pManhY3p7BA5ISsSuAxhUL/J+eu1IVKiWg0l0WcX5sdAGl6vH5zZTv9904q3vvHin0ZfHYAWut2iGsZ+00xAHXudL72CFTtpAAExIy148/T66WGMlmGCVqdxr5KMXBtuq+zIusP25ggAcK5/S4MOu85xPsZIycBtYJG5v08KjS9juhn3cU2KYuEIx/UvK8ySB4wDmGWS6A7SuEFCaT48DAX4a0QSYyQrd65askUcSD3ct7ZKETf9qqri25RIA/ydUuzzGyRgHX0El2k5ZYqFlaxRfUlxKWidyvMIBuvJo=
  file_glob: true
  file: build/alertmanager-webhook-fcm.*
  on:
    repo: jayme-github/alertmanager-webhook-fcm
    tags: true
    condition: "$LATEST = true"
- provider: script
  script: bash docker_push.sh
  on:
    repo: jayme-github/alertmanager-webhook-fcm
    tags: true
    condition: "$LATEST = true"
