language: go
sudo: required

env:
  global:
    - CGO_ENABLED=0
    - GO111MODULE=on
    - secure: "qM2yicBcxd3gt01/2othsHfzJK8tPTs1YqBl1Ss4m7lmt3OvPdAzkcDaKnmbrnUuIbVq8+PolyYbj7CI9VGUJj2XkR7FqwT9rD4ZyHpe0lmcK8RkX3KnL8JeBM7wmCKgISBexeskVlJNaFeZTlMjRt7GUKgnLCudl9hRq6f3C3lE8eAITtuHiWriK7Wo/m2nSJCxuG1WQG8LebJd8/5QnA5IyRAlEE6qCpB1yLuGKvSXPb4xEw9MVJJgw/SediYzAYbuvaS+qiUikdmHpFfOBJpSTtJM3R7y+IbRnBt7SGeZKGTi2D159H2F4i/eZjBhwyom/tmgRzQtw1OnqRA2GrkwT9Lqc5fEBU2txQso42Gn1JQ5MTd0fhyR7LWw2Wnc9r0WHD+MNU0Np1meDm6ar7TImOaDZWhBai6kpj8Of/Yucpy/AFyUJSV5yUTNKSO7TKbQMI1b9zlV9vz/YXfoPOIk8Rw960GOTAPJwIKQPfcG5dZ1S86P7DWHxx9JD7zd+5FG2FtPuOdbIt0FMqs4Dg9aQ6e2T4LhuWViIpj1pLWpjdFnSMxuG6YfRomr8q0HQwabm16iKEnRdFcBbnH4ebRlW1CMyGuVYfqYlQeDVYpjDevJQOkHld+RU/ypLMYROJCIbFqJXiYy8Lhrumxg7Ev7gty8YdW6ckqsSQTraFg="
    - secure: "LH1hsqpt/AQaMzqIsgKP3P3HHmwjZdBP/f2x9xhlTrYFu5nM1lK8P2jEDLmVnnnHiMK29pAMPp0yUqN6bD/UnQnH67tLKUlOLFfmVArD+JKlD1Ac/ch5CWCWtX7jbui8feGJnuuKlgg1OyDVPxYg5urLWN+8RH1RYZkW3hghP0zeeAi6Ge4la40H3e80wFl8pbVco6TYkPsBKQ87+ptJk1j68PNEqdLDhXE6Gnu3HDu+zB1DKg/NoBRnBnnVT7LhmvePEKT1IDhwQmgXrkpcL7woyuwKJKk6eoEoxxqnDJHbIqGqvXNn9PcUOuq0dX0NHhKWkcEAKvc/ydZPV0X4aLffb/evtXidIRCccBw0jis/QD+goXL1SkkHsfcv2s+pWlthErrnZpih8qvJ7reA7TfyxIKaul8aeqaoqU5NpjEnb94aS2K+kqQeOJ17q4gPJOSo7bK17oZJpZs5vkFPbX0Hw8/Diwesw2EhoibOVg4ZO+JBoCcPjK37Q5o4aQAfQ5T+jlBYzgKKdgom1qR6HDD/oGJobIwN+FCd1oJ8pw+Al+JlJF6k+R3k/s3A78vVd6kF7IiZGXTMpLA4Kl0MKOioA6Jn+5p+/yWok7c0/D4rEQkowGhKjfjzBwsjfKlCe3Y0RpzQMljNJO6LoGY1WMqPD5k2uQGyDgZHSo1dFc4="

services:
- docker

matrix:
  include:
  - go: 1.13.x
    env:
     - LATEST=true
  - go: tip
  allow_failures:
  - go: tip

install:
 - go mod download
 - go get github.com/mitchellh/gox

script:
 - go vet $(go list ./... | grep -v /vendor/)
 - go test -v ./...
 - if [ "${LATEST}" = "true" ]; then gox -os="linux darwin windows" -arch="amd64 386" -output="build/alertmanager-webhook-fcm.{{.OS}}.{{.Arch}}" -ldflags "-extldflags \"-static\" -X main.Rev=`git rev-parse --short HEAD`" -verbose ./...; fi
 - if [ "${LATEST}" = "true" -a -n "${TRAVIS_TAG}" ]; then docker build -t "jaymedh/alertmanager-webhook-fcm:${TRAVIS_TAG}" .; fi

deploy:
 - provider: releases
   skip_cleanup: true
   api_key:
     secure: D6zUa6GJWwyykS40t7CKitf8vuXqeGWQBpdE8cimcWmsWu158PIcEG6QNBIDBdZw8t2nxy6n9xqxKnYUYU4rw5UPu9hHCrTCEycMj07uVHvIOt74QU8js9cKjz2aD/Cm4huQDsgSIgy2mguC1qeKjjjGl4m0OKLfMWpB7F9m+1ysTKeghtRj40fzNPzVWeKOpCVBYlX/IvHBV+ObXy25dCOofoCD5QvQafRqQ6g0uRg5bqvDe9ZTly8JmbZhkc0eovxPMQQ7e8Q68nStz/ph+ME/iZEppCBc5JpDMHAlAPS4uO57ZOLsmqIZ8rBUNx+5nKy47z/ERueCezp8bwT2Bdz+SguP1IJSHNTMDilGzIC4VfKxaQE5GMwvkJG21mCG24ny2f5ZWDoXbRR7OdSN1B6wamNOfsMT/CYDfxtnoatkqhwepYtN8RWiBaMawwX/GhJib4xUM/n3lJC13K+c2q5moVdaryN270VdON4XdC+7mgZ9bklVzNFNYVAtAGlZi02AHa/BoTM73X0gtiK8JdgIXEZKLN6h3q0ufLbjRc6NAnyLiXi9B5UeTrKpx4g9lhbS9eKTvLim1gUVd2dyy3uw3mFBLXCjYhqeWzm4+8lwRwInV3iph9/raaYQ/bC7abxYO7zOo3cIeFx3NCltRLCQXpn4RQxJfYN09cYRlV8=
   file_glob: true
   file: build/alertmanager-webhook-fcm.*
   on:
     repo: jayme-github/alertmanager-webhook-fcm
     tags: true
     condition: "$LATEST = true"
 - provider: script
   script: bash docker_push.sh
   on:
     repo: jayme-github/alertmanager-webhook-fcm
     tags: true
     condition: "$LATEST = true"
